version: "3.7"
services:
  nexus:
    image: "sonatype/nexus3:3.19.1"
    container_name: "nexus"
    restart: always
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/nexus/nexus-data:/nexus-data:z
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "4"
  nginx:
    image: "nginx:1.17.6-alpine"
    container_name: "nginx"
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/ssl:/ssl:ro"
    depends_on:
      - nexus
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "4"